### PR TITLE
Refactor, Upgrade to newest versions of vscode, initial integration testing

### PR DESCRIPTION
**Pull request by mfelsche**
See https://code.visualstudio.com/updates/v1_36\#_splitting-vscode-package-into-typesvscode-and-vscodetest

This still needs to be verified to work, thus still a draft.

### CODE REVIEW

**Comment by Licenser** [comment]
is this thing still something we want to do?

**Comment by mfelsche** [comment]
Yes, I just didnt get to it yet...

**Comment by Licenser** [comment]
No worries, I just went through the PR/s tickets and tried to do a bit of cleanup :) and make sure the open PR's are still relevant

**Comment by Licenser** [comment]
if you rebase the should correctly run the tests, it seems cargo has a bug that requires bin tests to be run separately:

```
cargo test -p tremor-cli --bin tremor
```

will run them locally

**Review by darach — APPROVED** [review]
LGTM 🚀

**Pull request merged**
